site_name: exabyte.io documentation
theme_dir: exabyte_theme
extra_css:
    - app.css
    - extra.css
extra_javascript:
    - extra.js
site_favicon: /img/favicon.ico
copyright: © 2016 <a href="http://platform.exabyte.io">Exabyte Inc</a>. All rights reserved.
extra:
    home_url: https://platform.exabyte.io
    full_width: False
    preload_javascript:
        - preload.js
markdown_extensions:
    - toc:
        permalink: true
pages:

    - Home: index.md

    - Getting Started:
        - Creating materials:   getting-started/first-material-import.md
        - Running simulations:  getting-started/first-simulation.md
        - First Analytics:      getting-started/first-analytics.md
        - UI Overview:          getting-started/ui-overview.md
        - Billing Overview:     getting-started/billing-overview.md

    - Materials:
        - Creating an ideal crystal:    materials/creating-an-ideal-crystal.md
        - How to compare materials:     materials/how-to-compare-materials.md

    - Model & Method:
        - Models supported and planned: models/models-supported-and-planned.md

    - Compute:
        - Overview:           compute/overview.md
        - Queues:             compute/queues.md

    - Sharing & Collaboration:
        - Organizations and sharing of data:  collaboration/organizations-and-sharing-of-data.md

    - Command Line Interface:
        - Introduction:  cli/general.md
        - Login:         cli/login.md
        - Accounting:    cli/accounting.md
        - Environment:   cli/environment.md
        - Jobs:          cli/jobs.md
        - Extra:         cli/extra.md

    - Tutorials:
        - Quickstart:  tutorials/quickstart.md
        # - First Simulation:            tutorials/first-simulation.md

    - Accounts & Billing:
        - Settings and Profile:                         billing/settings-and-profile.md
        - Billing and Adding Credit:                    billing/billing-and-adding-credit.md
        - Pricing and Service Levels:                   billing/pricing-and-service-levels.md
        - How to increase your account balance:         billing/how-to-add-credit.md
        - How to upgrade your service level:            billing/how-to-upgrade-your-service-level.md
        - How to increase your storage quota:           billing/how-to-add-storage.md
    - Other:
        - Registration:     registration/registration.md

    - How to Participate:
        # - Student Program: participate/student-program.md
        # - Developer Program: participate/developer-programer.md
        - Trello Roadmap:   participate/trello-roadmap.md

    - Help & Support:
        - Phone/Email:  support/email.md
        - Helpdesk:     support/helpdesk.md
        - FAQ:          support/faq.md

    - Security:
        - Data Security in transfer: security/data-security-in-transfer.md
    #     - Data Security at rest: security/data-security-at-rest.md

    - Terminology:
        - Simulations:      terminology/simulations.md
