site_name: exabyte.io documentation
theme_dir: exabyte_theme
extra_css:
    - app.css
    - extra.css
extra_javascript:
    - extra.js
site_favicon: /img/favicon.ico
copyright: © 2015 Exabyte Inc. All rights reserved.
extra:
    home_url: https://platform.exabyte.io
    full_width: False

pages:
    # Home page - must be present
    - Home: 'index.md'
    # Web
    - Tutorials:
        - 'UI overview': 'tutorials/ui.md'
        - 'Quickstart':  'tutorials/quickstart.md'
    - Terminology:
    #     # Characteristic, descriptive, materials bank etc
    #     - 'Materials':        'terminology/materials.md'
    #     # Model, Method, Unit, Job, Workflow
        - 'Simulations':      'terminology/simulations.md'
    #     # Parameters that set up compute
    #     - 'Compute':          'terminology/compute.md'
    # Command-Line
    - Advanced:
        - 'Command-line (CLI)': 'cli/general.md'
        - 'CLI: Login':         'cli/login.md'
        - 'CLI: Accounting':    'cli/accounting.md'
        - 'CLI: Environment':   'cli/environment.md'
        - 'CLI: Batch jobs':    'cli/jobs.md'
        - 'CLI: Extra':         'cli/extra.md'
    - Billing:
        - 'Pricing':            'billing/pricing.md'
    # Other
    - Other:
        - 'FAQ': 'other/faq.md'
