site_name: exabyte.io documentation
theme_dir: exabyte_theme
extra_css:
    - app.css
    - extra.css
extra_javascript:
    - extra.js
site_favicon: /img/favicon.ico
copyright: © 2016 <a href="http://platform.exabyte.io">Exabyte Inc</a>. All rights reserved.
extra:
    home_url: https://platform.exabyte.io
    full_width: False
    preload_javascript:
        - preload.js
markdown_extensions:
    - toc:
        permalink: true
pages:

    - Home: index.md

    - Getting Started:
        - Creating materials:   getting-started/first-material-import.md
        - Running simulations:  getting-started/first-simulation.md
        - First Analytics:      getting-started/first-analytics.md
        - UI Overview:          getting-started/ui-overview.md
        - Billing Overview:     getting-started/billing-overview.md

    - Materials:
        - Creating an ideal crystal:    materials/creating-an-ideal-crystal.md
        - How to compare materials:     materials/how-to-compare-materials.md

    - Models & Methods:
        - Models supported and planned: models/models-supported-and-planned.md

    - Compute:
        - Overview:             compute/overview.md
        - Queues:               compute/queues.md

    - Sharing & Collaboration:
        - Organizations:        collaboration/organizations.md

    - Command Line Interface:
        - Introduction:         cli/general.md
        - Login:                cli/login.md
        - Accounting:           cli/accounting.md
        - Environment:          cli/environment.md
        - Jobs:                 cli/jobs.md
        - Extra:                cli/extra.md

    - Tutorials:
        - Quickstart:           tutorials/quickstart.md
        # - First Simulation:            tutorials/first-simulation.md

    - Accounts & Billing:
        - Settings and Profile:         billing/settings-and-profile.md
        - Billing and Payments:         billing/billing-and-payments.md
        - Pricing and Service Levels:   billing/pricing-and-service-levels.md
        - Storage Pricing:              billing/storage-pricing.md

    - Security:
        - Data Security in transfer:    security/data-security-in-transfer.md
    #     - Data Security at rest: security/data-security-at-rest.md

    - Other:
        - Registration:         other/registration.md
        # - Student Program: other/student-program.md
        # - Developer Program: other/developer-programer.md
        - Roadmap:              other/roadmap.md
        - Help & Support:       other/support.md
        - FAQ:                  other/faq.md

    - Terminology:
        - Simulations:          terminology/simulations.md
