site_name: exabyte.io documentation
theme_dir: exabyte_theme
extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css
    - extra.css
extra_javascript:
    # TODO: migrate away from parse
    # - https://www.parsecdn.com/js/parse-1.2.16.min.js
    - extra.js
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
site_favicon: /img/favicon.ico
copyright: © 2018 <a target="_blank" href="http://exabyte.io">Exabyte Inc</a>. All rights reserved. | <a target="_blank" href="http://platform.exabyte.io">Back to platform</a>
extra:
    version: "0.10.0"
    preload_javascript:
        - /preload_hotjar.js
        - /preload.js
markdown_extensions:
    - admonition
    - pymdownx.arithmatex
    - toc:
        permalink: true
pages:

    - Home: index.md

    - Getting Started:
        - Run first simulation:     getting-started/run-first-simulation.md
        - User interface overview:  getting-started/ui-overview.md
        - Content highlights:       getting-started/content-highlights.md
        - CLI job submission:       tutorials/cli-job.md

    - Data Convention:
        - Overview:                 data/overview.md
        - Structured data:          data/structured.md
        - Non-structured data:      data/non-structured.md

    - Materials:
        - Overview:                       materials/overview.md
        - Data:                           materials/data.md
        - Properties:                     materials/properties.md
        - Actions:
            - Advanced Search:            materials/advanced-search.md
            - Import:                     materials/import.md
            - Upload:                     materials/upload.md
            - Copy from shared bank:      materials/bank.md
            - Select During Job Creation: materials/selection.md
            - Other:                      materials/other-actions.md
            - Search & Compare:           materials/search-compare.md

    - Materials Designer:
        - Overview:                     materials-designer/overview.md
        - Header Menu:
            - Overview:                 materials-designer/header-menu/header-menu-intro.md
            - Input/Output:             materials-designer/header-menu/input-output.md
            - "Input/Output > Import":  materials-designer/header-menu/input-output/import.md
            - "Input/Output > Export":  materials-designer/header-menu/input-output/export.md
            - "Input/Output > Save":    materials-designer/header-menu/input-output/save.md
            - Edit:                     materials-designer/header-menu/edit.md
            - View:                     materials-designer/header-menu/view.md
            - Advanced:                 materials-designer/header-menu/advanced.md
            - "Advanced > Supercell":   materials-designer/header-menu/advanced/supercell.md
            - "Advanced > Combinatorial Set":  materials-designer/header-menu/advanced/combinatorial-set.md
            - "Advanced > Surface / Slab":     materials-designer/header-menu/advanced/surface-slab.md
            - Help:                     materials-designer/header-menu/help.md
        - Sidebar:
            - Items List:               materials-designer/sidebar-items.md
        - Source Editor:
            - Overview:                 materials-designer/source-editor-intro.md
            - Lattice Editor:           materials-designer/lattice.md
            - Basis Editor:             materials-designer/basis.md
        - 3D viewer:
            - Overview:                 materials-designer/viewer-intro.md
            - View features:            materials-designer/viewer-view.md
            - Edit features:            materials-designer/viewer-edit.md
            - Export features:          materials-designer/viewer-export.md

    - Workflows:
        - Overview:                       workflows/overview.md
        - Data:
            - Workflows:                  workflows/data.md
            - Subworkflows:               workflows/subworkflows.md
            - Units:                      workflows/units.md
            - Jobs:                       jobs.md
        - Actions:
            - Overview:                   workflows/actions-intro.md
            - Create:                     workflows/creating-workflows.md
            - Update:                     workflows/updating-workflows.md
            - Clone:                      workflows/clone.md
            - Open:                       workflows/open-edit.md
            - Copy from shared bank:      workflows/workflow-bank.md
            - Searching:                  workflows/searching.md
            - Other:                      workflows/other-actions.md
            #- Using workflows:            workflows/using-workflows.md
            - Adding Convergence:         workflows/convergence-algorithms.md
            - Adding Relaxation:          workflows/structural-relaxation.md
        # TODO: revise or remove
#        - Density Functional Theory:    workflows/density-functional-theory.md
#        - Example simulations:          workflows/example-simulations.md
#        - Advanced Properties:          workflows/advanced-characteristics.md

    - Workflow Designer:
        - Overview:                          workflow-designer/general-overview.md
        - Header Menu:
            - Overview:                      workflow-designer/header-menu-actions.md
        - Sidebar:
            - Items List:                    workflow-designer/sidebar-items.md
        #- Source Editor:
        #    - General Overview:             workflow-designer/source-editor-intro.md
        #    - Overview:                     workflow-designer/overview.md
        #    - Important Settings:           workflow-designer/important-settings.md
        #    - Detailed View:                workflow-designer/detailed-view.md
        #    - Compute:                      workflow-designer/compute.md


    - Compute:
        - Overview:                 compute/overview.md
        - Policies:                 compute/policies.md
        - Connection Options:       compute/connection-options.md
        - Levels & Queues:          compute/levels-queues.md
        - Hardware:                 compute/hardware.md
        - Actions:
            - Setting Parameters:   compute/setting-parameters.md
        - Command Line Interface:
            - Login:                cli/login.md
            - Accounting:           cli/accounting.md
            - Environment:          cli/modules-environment.md
            - Jobs:                 cli/jobs.md
            - "Jobs: example":      cli/jobs-example.md
            - Storage System:       cli/storage-system.md
            - Extra:                cli/extra.md
            - Permissions:          security/cli-users-permissions.md

    - Tutorials:
        # TODO: adjust with results closer to experiment and re-publish
        # - Semiconductors:
        #     - AlP Band Gap: tutorials/semiconductors/AlP-band-gap.md
        #     - III-V combinatorial screening: tutorials/semiconductors/III-Vs-band-gap.md
        - Pseudopotential DFT:
            - Upload a Pseudopotential:         tutorials/upload-pseudopotential.md
            - Electronic band structure:        tutorials/band-structure.md
            - Electronic band gap:              tutorials/band-gap.md
            - Electronic density of states:     tutorials/density-of-states.md
            - Electronic density mesh:          tutorials/electronic-density-mesh.md
            - Zero point energy:                tutorials/zero-point-energy.md
            - Structural relaxation:            tutorials/relaxation.md
            - K-point convergence:              tutorials/kpt-convergence.md
            - Fermi surface:                    tutorials/fermi-surface.md
        - Machine Learning:
            - Train ML Model:                   tutorials/train-ml-model.md
        - Other:
            - Custom-input workflow:            tutorials/custom-input-workflow.md
            - Restart from previous run:        tutorials/restart-job.md
            - Remote desktop visualization:     tutorials/remote-desktop.md
            - Job submission via terminal:      tutorials/cli-job.md
        # TODO: adjust combinatorial screening explanation according to latest UX
        # - Combinatorial-screening:          tutorials/combinatorial-screening.md
        # TODO: re-implement and re-enable Formation Energy
        # - Formation energy:                 tutorials/formation-energy.md
        # TODO: check relevance and update/delete
        # - CLI data import:                  tutorials/cli-job-import.md

    # separating to top-level b/c of the importance
    - Pricing:
        - Service Levels:               billing/pricing-and-service-levels.md
        - Storage Pricing:              billing/storage-quota.md

    - Accounts & Billing:
        - Settings and Profile:         billing/settings-and-profile.md
        - Billing and Payments:         billing/billing-and-payments.md
        - Actions:
            - Add payment method:       billing/add-credit-card.md
            - Check balance & quota:    billing/check-balance-quota.md
            - Increase account balance: billing/increase-balance.md
            - Increase quota:           billing/increase-quota.md
            - Upgrade Service Level:    billing/upgrade-service-level.md

    - Organizations:
        - Overview:         organizations/overview.md
        - Projects:         organizations/projects.md
        - Teams:            organizations/teams.md

    - Security:
        - Current State of Cloud Security:  security/current-state.md
        - Overview:                         security/overview.md
        - Security Policies:                security/security-policies.md
        - Threats Analysis:                 security/threats-analysis.md
        - Privacy:                          security/privacy-statement.md  # duplicate through link

    - Site Policy:
        - Privacy:                          site-policy/privacy-statement.md
        - Sharing:                          site-policy/sharing-policy.md
        - Terms of Service:                 site-policy/terms-of-service.md

    - REST-API:
        - Overview:                         rest-api/overview.md
        - Authentication:                   rest-api/authentication.md
        - Query structure:                  rest-api/query-structure.md
        - Endpoints:
            - Materials:                    rest-api/endpoints/materials.md
            - Materials-Bank:               rest-api/endpoints/materials-bank.md
            - Characteristics:              rest-api/endpoints/characteristics.md
            - Jobs:                         rest-api/endpoints/jobs.md
            - Workflows:                    rest-api/endpoints/workflows.md
            # TODO: revise and re-enable after
            # - Pseudos:                      rest-api/endpoints/pseudos.md
        - Python Client:                    rest-api/rest-api-python-client.md

    - Benchmarks:
        - High Throughput Screening:     benchmarks/high-throughput-screening.md
        - Distributed Memory Runs:       benchmarks/distributed-memory.md
        - Vendor Comparison:             benchmarks/vendor-comparison.md
        - High-Performance Linpack:      benchmarks/hpl-benchmark.md

    - Other:
        - FAQ:                  other/faq.md
        - Registration:         other/registration.md
        - Help & Support:       other/support.md
        - Community Programs:   other/community-programs.md
        - Terms of Service:     other/terms-of-service.md  # duplicate through link
        # - Student Program:    other/student-program.md
        # - Upcoming features:    other/upcoming-features.md
        # - Roadmap:              other/roadmap.md
        # Restricted content login page
        - restricted.md

    # - Terminology:
    #     - Simulations:              terminology/simulations.md
    #     - Materials Properties:     terminology/property-classification.md
    #     - Crystallography:          terminology/crystallography.md
