site_name: exabyte.io documentation
theme_dir: exabyte_theme
extra_css:
    - extra.css
    - https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css
extra_javascript:
    - extra.js
site_favicon: /img/favicon.ico
copyright: © 2016 <a href="http://platform.exabyte.io">Exabyte Inc</a>. All rights reserved.
extra:
    home_url: https://platform.exabyte.io
    full_width: False
    preload_javascript:
        - preload.js
markdown_extensions:
    - admonition
    - toc:
        permalink: true
pages:

    - Home: index.md

    - Getting Started:
        - Run first simulation:     getting-started/run-first-simulation.md
        - User interface overview:  getting-started/ui-overview.md

    - Materials:
        - Creating structures:          materials/creating-structures.md
        - Upload & Import:              materials/upload-and-import.md
        - Characteristic properties:    materials/characteristic-properties.md
        - Comparing materials:          materials/comparing-materials.md
        - Combinatorial sets:           materials/combinatorial-sets.md

    - Models & Methods:
        - Overview:                     models/overview.md
        - Advanced:                     models/advanced-characteristics.md
        - Convergence algorithms:       models/convergence-algorithms.md
        - Structural relaxation:        models/structural-relaxation.md
        - Combinatorial set input:      models/combinatorial-set-input.md
        - Density Functional Theory:    models/density-functional-theory.md
        - Simulation workflows:         models/simulation-workflows.md
        - Example simulations:          models/example-simulations.md

    - Compute:
        - Overview:             compute/overview.md
        - Queues:               compute/queues.md
        - Benchmarks:           compute/benchmarks-and-scalability.md
        - Connection:           compute/connection-options.md
        - Setting parameters:   compute/setting-parameters.md

    - Sharing & Collaboration:
        - Organizations:        collaboration/organizations.md
        - Organizations:        collaboration/create-organization.md
        - Invite Friends:       collaboration/invite-friends.md

    - Command Line Interface:
        - Overview:             cli/overview.md
        - Login:                cli/login.md
        - Accounting:           cli/accounting.md
        - Environment:          cli/modules-environment.md
        - Jobs:                 cli/jobs.md
        - Extra:                cli/extra.md

    - Tutorials:
        - Electronic band structure:        tutorials/band-structure.md
        - Electronic band gap:              tutorials/band-gap.md
        - Electronic density of states:     tutorials/density-of-states.md
        - Zero point energy:                tutorials/zero-point-energy.md
        - Formation energy:                 tutorials/formation-energy.md
        - Structural relaxation:            tutorials/relaxation.md
        - Automatic convergence:            tutorials/kpt-convergence.md
        - Combinatorial-screening:          tutorials/combinatorial-screening.md
        - Custom-input workflow:            tutorials/custom-input-workflow.md
        - Electronic density mesh:          tutorials/electronic-density-mesh.md
        - Fermi surface:                    tutorials/fermi-surface.md
        - Remote desktop visualization:     tutorials/remote-desktop.md
        - Job submission via terminal:      tutorials/cli-job.md
        - CLI data import:                  tutorials/cli-job-import.md

    - Accounts & Billing:
        - Settings and Profile:         billing/settings-and-profile.md
        - Billing and Payments:         billing/billing-and-payments.md
        - Pricing and Service Levels:   billing/pricing-and-service-levels.md
        - Storage Pricing:              billing/storage-quota.md
        - Add payment method:           billing/add-credit-card.md
        - Check balance & quota:        billing/check-balance-quota.md
        - Increase account balance:     billing/increase-balance.md
        - Increase quota:               billing/increase-quota.md
        - Upgrade Service Level:        billing/upgrade-service-level.md

    - Security:
        - Data Security in transfer:        security/data-security-in-transfer.md
        - Data Security at rest:            security/data-security-at-rest.md
        - CLI users permissions:            security/cli-users-permissions.md

    - Other:
        - Registration:         other/registration.md
        # - Student Program:    other/student-program.md
        # - Developer Program:  other/developer-program.md
        - Roadmap:              other/roadmap.md
        - Help & Support:       other/support.md
        - FAQ:                  other/faq.md

    - Terminology:
        - Simulations:          terminology/simulations.md
