site_name: exabyte.io documentation
theme_dir: exabyte_theme
extra_css:
    - app.css
    - extra.css
extra_javascript:
    - extra.js
site_favicon: /img/favicon.ico
copyright: © 2016 <a href="http://platform.exabyte.io">Exabyte Inc</a>. All rights reserved.
extra:
    home_url: https://platform.exabyte.io
    full_width: False
    preload_javascript:
        - preload.js
markdown_extensions:
    - toc:
        permalink: true
pages:

    - Home: index.md

    - Getting Started:
        - Run first simulation:     getting-started/run-first-simulation.md
        - User interface overview:  getting-started/ui-overview.md

    - Materials:
        - Creating structures:          materials/creating-structures.md
        - Upload & Import:              materials/upload-and-import.md
        - Characteristic properties:    materials/characteristic-properties.md
        - Comparing materials:          materials/comparing-materials.md

    - Models & Methods:
        - Overview:             models/overview.md

    - Compute:
        - Overview:             compute/overview.md
        - Queues:               compute/queues.md
        - Benchmarks:           compute/benchmarks-and-scalability.md
        - Connection:           compute/connection-options.md
        - Setting parameters:   compute/setting-parameters.md

    - Sharing & Collaboration:
        - Organizations:        collaboration/organizations.md

    - Command Line Interface:
        - Overview:             cli/overview.md
        - Login:                cli/login.md
        - Accounting:           cli/accounting.md
        - Environment:          cli/modules-environment.md
        - Jobs:                 cli/jobs.md
        - Extra:                cli/extra.md

    - Tutorials:
        - Electronic band structure:        tutorials/bandstructure.md
        # TODO by MH: add files below and corresponding explanations

        # - Electronic band gap:              tutorials/bandstructure.md
        # - Electronic density of states:     tutorials/bandstructure.md
        # - Zero point energy:                tutorials/bandstructure.md
        # - Formation energy:                 tutorials/bandstructure.md
        # - Structural relaxation:            tutorials/bandstructure.md

        # - Combinatorial-screening:          tutorials/bandstructure.md
        #        - enable combinatorial set
        #        - create a set with combinations for 3-5 semiconductors with unique names
        #        - create a set with permutations for a ~10 atom supercell with 2 dopants
        #        - submit both sets for execution
        #        - fast-forward
        #        - when finished navigate to analytics
        #        - find materials by Formula and compare bandgaps for both cases

        # - Custom-input workflow:            tutorials/bandstructure.md
        #       - remove extra units
        #       - open unit editor
        #       - paste content from elsewhere
        #       - save workflow under new name
        #       - run simulation

        # - Electronic density mesh:          tutorials/bandstructure.md
        #       - create job in web app
        #       - choose density mesh workflow
        #       - run the job
        #       - point out to remember the name of the job
        #       - connect via remote desktop
        #       - open Xcrysden
        #       - find the job directory and visualize mesh in XCrysden

        # - Fermi surface:                    tutorials/bandstructure.md
        #       - include explanation on how to visualize surface in XCrysden

        # - Remote desktop visualization:     tutorials/remote-desktop.md
        #       - use previously created input file for espresso
        #       - visualize it using XCrysden/Vesta

        # - Job submission via terminal:      tutorials/remote-desktop.md
        #       - connect in via web terminal
        #       - copy example input file from job templates folder
        #       - adjust input
        #       - submit the job
        #       - monitor status with qstat
        #       - tail output with tail
        #       - view job accounting information

        # - CLI data import:                  tutorials/remote-desktop.md
        #       - connect in via web terminal
        #       - copy example input file from job templates folder
        #       - adjust input to include `#PBS -web` pragma
        #       - submit the job
        #       - view progress on webapp
        #       - view files on webapp after finish

    - Accounts & Billing:
        - Settings and Profile:         billing/settings-and-profile.md
        - Billing and Payments:         billing/billing-and-payments.md
            # Include:
            # - Add payment method:         add-card-and-credit.md
            # - Increase account balance:   increase-balance.md
        - Pricing and Service Levels:   billing/pricing-and-service-levels.md
            # Include:
            # - Adjust service level:       adjust-service-level.md
        - Storage Pricing:              billing/storage-quota.md
            # Include:
            # - Check balance & quota:      check-balance-quota.md
            # - Increase quota:             increase-quota.md

    - Security:
        - Data Security in transfer:    security/data-security-in-transfer.md
        - Data Security at rest:        security/data-security-at-rest.md

    - Other:
        - Registration:         other/registration.md
        # - Student Program:    other/student-program.md
        # - Developer Program:  other/developer-program.md
        - Roadmap:              other/roadmap.md
        - Help & Support:       other/support.md
        - FAQ:                  other/faq.md

    - Terminology:
        - Simulations:          terminology/simulations.md
