site_name: exabyte.io documentation
theme_dir: exabyte_theme
pages:
- ['index.md', 'Home']
# FAQ
- ['faq/index.md', 'FAQ', 'FAQ']
# Web
- ['tutorials/first-steps.md', 'Tutorials', 'Quickstart']
# Command-Line
- ['cluster/index.md', 'Advanced', 'Compute Platform (CP)']
- ['cluster/general.md', 'Advanced', 'CP:Overview']
- ['cluster/accounting.md', 'Advanced', 'CP:Accounting']
- ['cluster/environment.md', 'Advanced', 'CP:Environment']
- ['cluster/jobs.md', 'Advanced', 'CP:Jobs']
- ['cluster/jobs-angstrom.md', 'Advanced', 'CP:Jobs-angstrom']
