name: Build tests and GitHub release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-py-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-24.04"]
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          submodules: true

      - name: Setup python 3
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build documentation
        uses: Exabyte-io/action-mkdocs-build@main

  publish-py-package:
    needs:
      - run-py-tests
    runs-on: ubuntu-24.04
    if: (github.repository != 'Exabyte-io/template-definitions-js-py') && (github.ref_name == 'master')

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Checkout actions repository
        uses: actions/checkout@v4
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions

      - name: Publish python release
        uses: ./actions/py/publish
        with:
          python-version: "3.10"
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          publish-tag: "true"
          publish-to-pypi: "false"
