name: Build tests and GitHub release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-24.04"]
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          submodules: true

      - name: Setup python 3
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build documentation
        uses: Exabyte-io/action-mkdocs-build@main

  github-release:
    runs-on: ubuntu-24.04
    if: github.ref_name == 'master'
    needs: [tests]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout actions repository
        uses: actions/checkout@v4
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions

      - name: Configure repository
        uses: ./actions/git/config
        with:
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}

      - name: Determine git tag
        id: get-tag-name
        uses: ./actions/git/version

      - name: Publish new git tag and release
        uses: ./actions/git/release
        with:
          tag-name: ${{ steps.get-tag-name.outputs.tag-name }}
