name: Build documentation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        python-version: ["3.8", "3.9"]
    steps:
      - uses: actions/checkout@v4
      - name: setup python 3
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup project dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends curl git git-lfs
          git lfs pull
          git submodule update --recursive --init
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: build documentation
        run: mkdocs build
