name: Update S3 sources
on:
  pull_request:
    types: closed
  workflow_dispatch:
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Checkout LFS objects
        run: git lfs pull

      - uses: actions/setup-python@v2
        with:
          python-version: 'pypy-2.7'

      - name: Build pages
        uses: Exabyte-io/action-mkdocs-s3-publish@main

      - name: S3 Sync
        uses: Exabyte-io/action-install-aws-cli@master
      - run: aws s3 sync site/ s3://docs.mt3ra.com/
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.S3_LOCATION }}
