name: Update
on:
  pull_request:
    types: closed
  workflow_dispatch:
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true

      - uses: actions/setup-python@v2
        with:
          python-version: 'pypy-2.7'

      - name: Build pages and publish to S3
        uses: dmitry-spodarets/mkdocs-s3-publish-action@main
        env:
          S3_LOCATION: ${{ secrets.S3_LOCATION }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
