name: Update S3 sources
on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 1 1 *'
  workflow_dispatch:
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-22.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          submodules: true

      - name: Set python 3 version
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Build pages
        uses: Exabyte-io/action-mkdocs-build@main

      - name: S3 Deploy
        uses: Exabyte-io/action-s3-deploy@v3
        with:
          folder: site
          bucket: docs.mat3ra.com
          bucket-region: ${{ secrets.S3_LOCATION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /*
          no-cache: true
          private: true
